inc/class-comment-hacks.php
Instead of checking for 'a comment' to be in the system (draft, unapproved) checking for approved comments has a more natural experience for the user.
Situation:
- Visitor enters a comment
- Shown the thank-you page
- Adds another comment without being approved yet
- Returns to the page with the #{comment-id} hash, but the comment is not there yet (not approved)
Feels like something went wrong.
=> Check for approved comments

admin/class-comment-parent.php
[Broken Link Checker](https://wordpress.org/plugins/broken-link-checker/) uses AJAX as well, but obviously with different nonces.
=> Make Yoast Comment Hacks compatible with Broken Link Checker

inc/class-comment-form-hacks.php
To make sure we can place and style the comment, It adds a span with a class.
1. check out the branch
2. check if the span is visible when trying to comment on a post.
3. it should not change the design in any way.
=> Adds span to the comment-policy sentence

admin/views/comment-parent-box.php, admin/views/config-page.php
These were the two odd ones out while the tag in all the other files is consistent.
=> Documentation: use consistent package names

admin/class-admin.php, admin/views/config-page.php, inc/class-comment-hacks.php
Hooks should be documented using a docblock which includes a summary, an optional description and information on the parameters passed.
Ref: https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters
=> Documentation: improve action/filter hook documentation

.travis.yml
The `composer install` is run conditionally based on the `CHECK` ENV variable which is only set on a high PHP version (7.3), so no need to account for PHP 5.2 here.
=> Travis: minor clean up

admin/class-admin.php, admin/class-comment-parent.php, yoast-comment-hacks.php
`include` and `require` are language constructs, not functions.
With that in mind there are a number of best practices surrounding them:
* There is no need to use parenthesis and not doing so will be, albeit marginally, faster.
* Always pass an absolute path for maximum portability. The `yoast-comment-hacks.php` file defines the `YST_COMMENT_HACKS_PATH` constant to be used for that (includes trailing slash), WP itself has `ABSPATH` (includes trailing slash).
* As all the relevant PATH constants already contain a trailing slash, there is no need for a slash at the start of the text string pointing to the exact file to be included.
=> CS: review of all include and require statements

inc/class-comment-hacks.php
Based on `YoastCommentHacksAdmin::options_validate()`, the value of `redirect_page` should be an integer, so doing a strict, integer based comparison should work fine.
Highly recommended!
---
NOTE: build failure is unrelated to this PR. See: https://travis-ci.org/Yoast/comment-hacks/jobs/546676738
=> QA: use strict comparisons

admin/views/config-page.php
While this `view` should only be included from within a method in the Comment Hacks plugin, there is no guarantee it will be.
So the variable declaration should be treated like a global variable, which it would be if it wouldn't be included from within a function.
So, I've renamed the variable.
The variable was also being escaped for use in an HTML attribute at declaration. This was unnecessary as wherever it is used, it was also escaped and in a better way - i.e. escaping the complete string in one go instead of escaping parts of a string in individual pieces.
I expect no problems, but never a bad idea to test it anyway. Would be a case of loading the config page and checking that everything still works and looks the same as before.
=> CS: prefix a "global" variable

admin/class-admin.php
By loading scripts in the footer of a page, the page rendering is not blocked by the script download.
Includes minor code layout reformatting for readability.
* Added `grunt shell:phpcs` override. Travis failed when calling `vendor/squizlabs/php_codesniffer/scripts/phpcs` (defined in `@yoast/plugin-grunt-tasks`) but in this version of php_codesniffer it is located in `vendor/squizlabs/php_codesniffer/bin/phpcs`.
Highly recommended!
=> CS: load script in a non-page-render-blocking manner

admin/views/config-page.php
As this should always be an integer, this is pretty simple to secure.
=> QA/Output escaping: remove whitelisting

.travis.yml, composer.json, composer.lock, readme.txt, yoast-comment-hacks.php
Includes:
* Adjusting the `Requires...` info in the `readme.txt` file.
* Removing builds against PHP < 5.6.
* Adding a build against PHP 7.4 and `nightly` (PHP 8).
The `nightly` build is allowed to fail for now.
* Removing the `xrstf/composer-php52` dependency and references to the  `vendor/autoload_52.php` file.
As the Comment Hacks plugin does not contain unit tests, these changes can already be made and made in one go.
Also:
* Travis hasn't supported `sudo` for quite a while now, so removing it.
Note: the build failure is unrelated to this PR.
Related to https://github.com/Yoast/wordpress-seo/issues/13758
=> Stop explicit support for PHP < 5.6 /  WP < 5.2

.phpcs.xml.dist, admin/admin.php, admin/comment-parent.php, admin/views/config-page.php, composer.json, composer.lock, inc/clean-emails.php, inc/email-links.php, inc/forms.php, inc/hacks.php, inc/length.php, inc/notifications.php
This updates the dependency in `composer.json`, as well as the PHPCS ruleset for YoastCS 2.0.0.
Includes:
* A selective update of the `composer.lock` for just YoastCS and its dependencies.
* Removing the tweaks to the Composer `check-cs` script to allow for PHP >= 5.6.
PHP 5.6 is now the minimum PHP version everywhere.
Ref: https://github.com/Yoast/yoastcs/releases/tag/2.0.0
This deprecates the `yoast_comment_hacks_notification_roles` filter hook in favour of the `Yoast\WP\Comment\notification_roles` hook.
[This needs a changelog entry]
This deprecates the `yoast_ch_admin_footer` action hook in favour of the `Yoast\WP\Comment\admin_footer` hook.
[This needs a changelog entry]
This deprecates the `yoast_comment_redirect` filter hook in favour of the `Yoast\WP\Comment\redirect` hook.
[This …
=> PHPCS: Update to YoastCS 2.0.0

inc/forms.php
As the property is not used by this class, setting it is redundant.
=> QA: remove unused private property

admin/admin.php, inc/clean-emails.php, inc/email-links.php, inc/hacks.php, inc/length.php
PHP has no concept of named return variables, so the name of the variable has no value in the `@return` tag.
=> Docs: various minor fixes

admin/admin.php
The code was already in place to load the minified vs non-minified file based on whether `SCRIPT_DEBUG` is set or not, the `$min` variable just wasn't used.
To test this change:
* Define the constant `SCRIPT_DEBUG` in `wp-config.php` and set it to `true`.
* While on `trunk`, load the comment hacks admin page.
* Do a "view source" on the JS file and see a minified unreadable mess.
* Switch to this branch, reload the admin page.
* Check the JS source again and you should see human readable output.
Note: I haven't tested this and these test instructions presume that grunt build has been run and the minified file exists (then again, the original code also presumed that).
=> Fix js loading / allow for script debug

admin/admin.php, inc/email-links.php, inc/hacks.php, inc/length.php
Import `use` statements for classes in the same namespace will not be allowed.
=> CS: revert "always use `use` statements"

composer.json, composer.lock
* Updated YoastCS from `2.0.2` to `2.1.0`.
* Updated PHP_CodeSniffer from `3.5.5` to `3.5.8`.
* Updated the DealerDirect Composer plugin from `0.6.2` to `0.7.0` (which is compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Relevant changes in PHPCS:
* PHPCS will now _run_ without problems on PHP 8.
Note: it will not necessarily handle all code using PHP 8 syntax correctly yet, though it does contain preliminary support for various syntaxes.
* Lots of bugfixes.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/2.1.0
* https://github.com/squizlabs/php_codesniffer/releases
Update the Composer Installers dependency …
=> Composer: update YoastCS and Composer Installers

admin/admin.php, inc/hacks.php
Variety of fixes:
* Use fully qualified function calls to global functions in namespaced files.
* Use fully qualified global constants in namespaced files.
* Tag order in function docblocks
* Consistently use one comment style for translators comments - `/* ... */` is preferred.
When multiple styles are mixed, most PO generators will only pull out one type, not both.
* Minor whitespace fixes.
=> CS: clean up after merges

inc/clean-emails.php, inc/email-links.php
In WordPress 5.5, the default `comment_type` was changed from an empty string to `comment`. This had some impact for all the features that still had checks in place for an empty string. This PR just updates a few places in the codebase where an empty string was assumed to be the value for a `comment_type of type` "comment".
The changes in this PR are based on two assumptions that look legitimate:
- No need for backward compatibility. The change in WordPress 5.5 also introduced an upgrade routine to update all `content_type` empty strings to `comment`. See the related change: https://core.trac.wordpress.org/changeset/47597. The upgrade routine ran on a scheduled event. WordPress 5.5 was released on August 11, 2020 and it's safe to assume this value has been on all 5.5 installations out …
=> Adjust comment type checks for WP 5.5 and later.

.github/workflows/lint.yml
... so builds against PHP 8.1 should no longer be allowed to fail.
=> GH Actions: PHP 8.1 has been released

.github/workflows/cs.yml, .github/workflows/js.yml, .github/workflows/lint.yml, grunt/config/shell.js
The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Refs:
* https://github.com/ramsey/composer-install/releases/
As these scripts are supposed to be run "under the hood" in both local dev, as well as CI, adding `--no-interaction` to Composer commands to potentially prevent CI hanging if, for whatever reason, interaction would be needed in the future.
(used in inline script documentation)
=> GH Actions: minor tweaks

.github/workflows/js.yml
The `setup-node` action has released a new major.
This upgrades the JS workflow to use this new action runner.
Ref: https://github.com/actions/setup-node/releases/tag/v3.0.0
=> GH Actions: update setup-node action runner

.gitattributes, .github/workflows/test.yml, .gitignore, .phpcs.xml.dist, .removeable-files, composer.json, composer.lock, inc/clean-emails.php, phpunit.xml.dist, tests/bin/install-wp-tests.sh, tests/bootstrap.php, tests/inc/clean-emails-test.php, tests/testcase.php
This commit adds all the necessary prerequisites to the package to allow for adding tests.
* Adds WP Test Utils as a dev dependency.
This will add PHPUnit, PHPUnit Polyfills and BrainMonkey.
* Adds an `autoload-dev` directive to allow for autoloading test files.
* Adds a `config-platform` directive to ensure that the dependencies in the `composer.lock` file will comply with the minimum supported PHP requirement.
When different versions of the test utilities are needed, a selective update can be executed in CI, but the locked dependencies should always be compatible with the minimum supported PHP version.
* Adds a `test` script to allow for running the tests using `composer test`.
* Exclude files related to the tests from distribution archives.
* Prevent a `phpunit.xml` overload file from …
=> QA: create a test setup for the plugin

.github/workflows/cs.yml, .github/workflows/js.yml, .github/workflows/lint.yml, .github/workflows/security.yml, .github/workflows/test.yml
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
=> GH Actions: version update for various predefined actions

.github/workflows/test.yml, readme.txt
Sets minimum WordPress version to 5.9 and tested up to 6.0.
=> Sets minimum WordPress version to 5.9 and tested up to 6.0.

admin/admin.php, composer.lock
PHPCS has had a few releases since the last update. These mostly add syntax support for PHP 8.1.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/releases
=> Composer: update PHPCS

.github/workflows/test.yml
PR #93 dropped support for WP < 5.9, which means the work-around which were in place for running the tests on older WP versions are no longer needed.
This commit removes those completely.
Ref: Yoast/comment-hacks#93
=> GH Actions/test: clean up script after dropping support for WP 5.9

.github/workflows/cs.yml, .github/workflows/js.yml, .github/workflows/lint.yml, .github/workflows/test.yml
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
Make sure branch names in the branch selection are correct to ensure builds will still run when appropriate.
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The …
=> GH Actions: various tweaks

.phpcs.xml.dist, admin/comment-parent.php, inc/clean-emails.php, inc/email-links.php
Fixes #50 by replacing all queries with proper core code usage.
=> Fix DB issues

inc/hacks.php
There's no test framework, so I couldn't write a unit test.
=> Null safety for `network_home_url` without hostname

admin/admin.php
I don't have the energy to fill in the entire pull request template.
The target class is already within the same. I removed the import of the non-existing one.
Cheers!
* Fixes a bug where a non-existing class was imported and used.
This PR can be summarized in the following changelog entry:
* Fixes a bug where a non-existing class was imported and used.
*
Fixes #
=> Removed class import

.github/workflows/composer-diff.yml, .github/workflows/phpstan.yml, .github/workflows/test.yml, .github/workflows/wp-version-checker.yml, admin/admin.php, admin/comment-parent.php, admin/views/comment-parent-box.php, admin/views/config-page.php, composer.json, composer.lock, inc/autoload.php, inc/clean-emails.php, inc/email-links.php, inc/forms.php, inc/hacks.php, inc/length.php, inc/notifications.php, phpstan.neon.dist, readme.txt
* Added PHPStan
* Updated WPCS to 3.1
* Fixed errors
* Updated tested up to WP version
* Update WP version matrix
Fixes #
=> WPCS 3.1, PHPStan and workflows

inc/hacks.php
When going through broken links you'd have to look in the source to find a broken comment author link, with this change, we display it so it's easier to find.
=> Make it easier to find comment author urls

.phpcs.xml.dist, admin/admin.php, admin/assets/css/comment-hacks.css, admin/views/config-page.php, comment-hacks.php, inc/hacks.php, inc/progress-planner/comment-policy.php, inc/progress-planner/comment-redirect.php, package.json, readme.md, readme.txt, tests/bootstrap.php
* This renames the plugin from "Comment Hacks" to "Comment Experience"
* Adds a link to the "Comment Experience" settings on the `options-discussion.php` settings page.
* Adds an option to redirect repeat commenters, just like first time commenters.
=> Switch plugin to comment-experience instead of comment-hacks & more

inc/progress-planner-tasks.php, phpstan.neon.dist
In v1.1.1 of progress-planner we changed the structure of providers, and some things are not backwards-compatible.
This PR adds a check to avoid adding providers if the PP version is older than 1.1.1 in order to avoid conflicts and PHP errors in case the user updates comment-experience before updating progress-planner
=> Do not add PP providers if PP version is older than 1.1.1

inc/progress-planner/comment-policy.php, inc/progress-planner/comment-redirect.php
Links are [mistakenly change](https://github.com/ProgressPlanner/comment-hacks/commit/bda0e4c8809ea81c40b3a2dafb0fee26455835ae) when changes for v2.1.2 were merged.
=> Fix links for Progress Planner tasks

inc/hacks.php
Plugin [sets defaults & runs upgrade method](https://github.com/ProgressPlanner/comment-hacks/blob/366d7e725213afa1951778deaccab7a620f9f1e8/inc/hacks.php#L30) if the version is not set or it's lower than then defined in the main plugin file.
But then in the upgrade method it [sets the version](https://github.com/ProgressPlanner/comment-hacks/blob/366d7e725213afa1951778deaccab7a620f9f1e8/inc/hacks.php#L299) only if it is not previously set.
Meaning that once plugin is updated to the next version it will run set_defaults & upgrade on every page load.
This PR fixes that and runs the upgrade routine only when plugin version is increased.
=> Run upgrade routine only when plugin version is increased

phpunit.xml.dist
When I ran tests there was a message:
```
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```
This PR migrates the XML configuration.
=> Migrate PHPUnit XML schema

admin/admin.php, inc/forms.php, inc/hacks.php, readme.txt
Similar to the https://github.com/ProgressPlanner/comment-hacks/pull/145 , translatable strings which are added as the Options defaults are set to early.
This PR delays all calls to the `Hacks::get_defaults` to the `init` hook.
=> Delay translatable strings

inc/progress-planner-tasks.php, inc/progress-planner/comment-moderation.php, inc/progress-planner/comment-policy.php, inc/progress-planner/comment-redirect.php, phpstan.neon.dist
This PR makes plugin compatible with the Progress Planner v1.4.
Besides the PHP deprecation notices, because of the classes structure changed, it triggered the fatal error as well.
Reason is that we had this check inside the class file:
```
if ( ! \class_exists( '\Progress_Planner\Suggested_Tasks\Local_Tasks\Providers\Repetitive' ) ) {
return;
}
```
So the class gets instantiated, autoloader loads the file but then there is an early exit - which triggers PHP fatal error since instantiated class is not defined.
For the reason I have moved the check the filter itself, so it's checked at once for all the tasks.
=> Compatibility with the upcoming Progress Planner v1.4
